title: Lucca Medievale
email: luccamedievale@consanpaolino.org
description: |
  Festa medievale con il villaggio degli artigiani,
  spettacoli di strada, torneo dei balestrieri e scontri fra uomini d'arme
baseurl: ""
url: "https://luccamedievale.it"
logo: /assets/images/lucca-medievale-logo.jpg
lang: it_IT
google_analytics: UA-107557-21
social:
  name: Lucca Medievale
  links:
    - https://twitter.com/consanpaolino
    - https://www.facebook.com/consanpaolino/
    - https://www.facebook.com/luccamedievale/
    - https://www.instagram.com/consanpaolino/
    - https://plus.google.com/+ConsanpaolinoOrg
    - https://t.me/consanpaolino
credits: |
  Associazione Contrade San Paolino<br/>
  Casermetta San Paolino, Viale delle Mura Urbane<br/>
  55100 Lucca<br/>
  luccamedievale@consanpaolino.org
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
