title: Lucca Medievale
email: consanpaolino@gmail.com
description: |
  Evento annuale con villaggio medievale degli artigiani,
  spettacoli di strada, torneo dei balestrieri e combattimenti all'arma bianca
baseurl: ""
url: "https://luccamedievale.it"
google_analytics: UA-107557-21
social:
  name: Lucca Medievale
  links:
    - https://www.facebook.com/luccamedievale/
credits: |
  Associazione Contrade San Paolino<br/>
  Sortita Porta San Pietro, 1/3<br/>
  55100 Lucca<br/>
  consanpaolino@gmail.com
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
