title: Lucca Medievale
email: segreteria@promo-terr.it
description: Evento annuale con mostra mercato, spettacoli di strada, torneo dei balestrieri
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-107557-21
credits: |
  Promo-Terr<br/>
  Via Verdi 121<br/>
  55049 Viareggio<br/>
  segreteria@promo-terr.it
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed