title: Lucca Medievale
description: Mostra Mercato, spettacoli di strada, torneo dei balestrieri
theme: jekyll-theme-cayman
google_analytics: UA-107557-21
credits: |
  Associazione Contrade San Paolino

  Sortita Porta S. Pietro, 1/3

  55100 Lucca LUy
