title: Lucca Medievale
description: Evento annuale con mostra mercato, spettacoli di strada, torneo dei balestrieri
theme: jekyll-theme-cayman
google_analytics: UA-107557-21
credits: |
  Associazione Contrade San Paolino<br/>
  Sortita Porta S. Pietro, 1/3<br/>
  55100 Lucca LU
